CREATE TABLE [dbo].[Kala_Mahsol]
(
[ID] AS (CONVERT([bigint],concat(ascii(substring([Code],(1),(1))),ascii(substring([Code],(2),(1))),ascii(substring([Code],(3),(1))),ascii(substring([Code],(4),(1))),right([Code],(3))),(0))) PERSISTED,
[Name] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Code] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Sharh] [nvarchar] (150) COLLATE Persian_100_CI_AS NULL,
[Code_tedad] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Code_parvaneh_sakht] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Barcode] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Start_point1] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[start_point2] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Start_point_3] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Start_point4] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[vahed] [nvarchar] (15) COLLATE Persian_100_CI_AS NULL,
[Vazn_karton] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Code_meli] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Vazn] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Code_groh_kala] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Vorodi_riali] [decimal] (18, 0) NULL,
[vorodi_Tedadi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Khoroji_riali] [decimal] (18, 0) NULL,
[Khoroji_tedadi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[End_point1] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[End_point2] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[End_point3] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[End_point4] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Start_riali] [decimal] (18, 0) NULL,
[End_riali] [decimal] (18, 0) NULL,
[Shomareh] [decimal] (18, 0) NULL,
[Name_tejari] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[lock] [bit] NULL,
[Noae_bastehbandi] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Last_code] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[active] [bit] NULL,
[username] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[machine] [nvarchar] (40) COLLATE Persian_100_CI_AS NULL,
[date_time] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Flag_edit] [int] NULL,
[User_Edit] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Ghafaceh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Radif] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Tabagheh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Code_Elmi] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Noae_Moshtari] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[Modat_zaman] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[Name_sherkat_sazandeh] [nvarchar] (70) COLLATE Persian_100_CI_AS NULL,
[Shamsi_OR_Miladi] [bit] NULL,
[Is_Fifo] [int] NULL,
[Counter] [bigint] NOT NULL IDENTITY(1, 1),
[Code_Tamin] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[code_behdasht] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Is_Daroee] [bit] NULL,
[IRC] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[RasmiCode] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Fehrest] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[GenericCode] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[INN] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[GTIN] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Name_Generic_EN] [nvarchar] (100) COLLATE Persian_100_CI_AS NULL,
[Name_Generic_FA] [nvarchar] (100) COLLATE Persian_100_CI_AS NULL,
[AppName] AS (app_name()),
[Hajm_karton] [decimal] (18, 4) NULL,
[ID_Tafsil] [bigint] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Kala_Mahsol] ON [dbo].[Kala_Mahsol] ([active]) INCLUDE ([Code], [Code_tedad], [ID], [Name], [Vazn]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Kala_Mahsoltt] ON [dbo].[Kala_Mahsol] ([ID], [active]) INCLUDE ([Code], [Code_tedad], [Name], [Vazn]) ON [PRIMARY]
GO
