CREATE TABLE [dbo].[moshtari]
(
[noae] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[code] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[name] [nvarchar] (500) COLLATE Persian_100_CI_AS NULL,
[name_khanevadegi] [nvarchar] (500) COLLATE Persian_100_CI_AS NULL,
[name_foroshghah] [nvarchar] (500) COLLATE Persian_100_CI_AS NULL,
[ostan] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[shahr] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[khyaban_asli] [nvarchar] (500) COLLATE Persian_100_CI_AS NULL,
[khyaban_farei] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[kocheh] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[midan] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[pelak] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[code_tel] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[tel1] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[tel2] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Fax] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[mob1] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[mob2] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[vaziyt_melk] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[code_posti] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Shomareh_sabt] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Code_meli] [nvarchar] (20) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[Shomareh_senfi] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_nahieh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Shomareh_mantagheh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Shomareh_dar_nahieh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Code_eghtesadi] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[groh] [nvarchar] (4) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[noae_takhfif] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[hadeaksar_etebar_riali] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[tozihat] [nvarchar] (200) COLLATE Persian_100_CI_AS NULL,
[active] [bit] NULL,
[username] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[machine] [nvarchar] (40) COLLATE Persian_100_CI_AS NULL,
[date_time] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[code_hesabdari_ghadim] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Face_Adres] [nvarchar] (300) COLLATE Persian_100_CI_AS NULL,
[Face_name] [nvarchar] (100) COLLATE Persian_100_CI_AS NULL,
[Code_AB] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Code_Shahr] [nvarchar] (5) COLLATE Persian_100_CI_AS NULL,
[Code_Ostan] [nvarchar] (5) COLLATE Persian_100_CI_AS NULL,
[Counter] [bigint] NOT NULL IDENTITY(1, 1),
[Shenase_Banki] [nvarchar] (17) COLLATE Persian_100_CI_AS NULL,
[GLN_Code] [nvarchar] (13) COLLATE Persian_100_CI_AS NULL,
[HIX_Code] [nvarchar] (11) COLLATE Persian_100_CI_AS NULL,
[DEFAULT_hadeaksar_etebar_riali] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[AppName] [nvarchar] (128) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[SaleCode] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[RasteCode] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[ID_Tafsil] [bigint] NULL,
[ProviderNo] [bigint] NULL,
[CodeGrohDarokhane] [tinyint] NULL,
[PersonType] [tinyint] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ixMoshtari] ON [dbo].[moshtari] ([Code_meli], [groh], [active]) ON [PRIMARY]
GO
