CREATE TABLE [dbo].[darkhast]
(
[shomareh_darkhast] [nvarchar] (11) COLLATE Persian_100_CI_AS NULL,
[shomareh_serial] [nvarchar] (11) COLLATE Persian_100_CI_AS NULL,
[code_foroshghah] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[groh_moshtary] [nvarchar] (3) COLLATE Persian_100_CI_AS NULL,
[code_vizitor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[mantagheh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[masir] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[sharit_tasvieh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[modat_chek] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[tozihat] [nvarchar] (max) COLLATE Persian_100_CI_AS NULL,
[noae_factor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[noae] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_factor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[tarikh_vosol] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_havaleh_khoroji] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_taghir] [int] NULL,
[mablagh] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[temp_mablagh] [decimal] (18, 0) NULL,
[noa_tasfieh] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[vazn] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_Dr_Vazn] DEFAULT ((0)),
[tedad_karton] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_tedad_karton] DEFAULT ((0)),
[sharayete_tasfieh] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[tarikh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[noe_darkhast] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[gymat_kol_darkhast] [bigint] NULL,
[code_noae] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[takhfif_jenci] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[takhfif_naghdi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[takhfif_noe] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[bargashti] [decimal] (18, 0) NULL,
[Tedad_print] [int] NULL,
[mablage_jayze_jenci] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[mablage_jayze_nagdi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Flag_edit] [int] NULL,
[User_Edit] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Flag_submit] [int] NULL,
[User_submit] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Datetime_submit] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[active] [bit] NULL,
[date_time] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[username] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[machine] [nvarchar] (40) COLLATE Persian_100_CI_AS NULL,
[Datetime_Create] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[User_Create] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[Rasteh] [int] NULL,
[Rate] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Darsad_Takhfif_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_DR_Darsad_Takhfif_Saderat] DEFAULT ((0)),
[Takhfif_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_DR_Takhfif_Saderat] DEFAULT ((0)),
[Add_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_DR_Add_Saderat] DEFAULT ((0)),
[Darsad_Add_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_DR_Darsad_Add_Saderat] DEFAULT ((0)),
[Counter] [bigint] NOT NULL IDENTITY(1, 1),
[IsBasket] [bit] NULL,
[StartTime] [datetime2] NOT NULL CONSTRAINT [DF__darkhast__StartT__0D4C1E6B] DEFAULT (sysutcdatetime()),
[EndTime] [datetime2] NOT NULL CONSTRAINT [DF__darkhast__EndTim__0E4042A4] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[IsFestival] [bit] NULL,
[AutoTransfer] [bit] NULL,
[IsOmdeh] [bit] NULL,
[ID_Tablet] [int] NULL,
[AppName] [nvarchar] (max) COLLATE Persian_100_CI_AS_SC_UTF8 NULL
) ON [PRIMARY]
GO
