CREATE TABLE [dbo].[factor]
(
[shomareh_darkhast] [nvarchar] (11) COLLATE Persian_100_CI_AS NULL,
[shomareh_serial] [nvarchar] (11) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[code_foroshghah] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[groh_moshtary] [nvarchar] (3) COLLATE Persian_100_CI_AS NULL,
[code_vizitor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[mantagheh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[masir] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[sharit_tasvieh] [tinyint] NULL,
[modat_chek] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[tozihat] [nvarchar] (max) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[noae_factor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[noae] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_factor] [int] NULL,
[tarikh_vosol] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[shomareh_havaleh_khoroji] [int] NULL,
[shomareh_taghir] [tinyint] NULL,
[mablagh] [bigint] NULL,
[temp_mablagh] [bigint] NULL,
[noa_tasfieh] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[vazn] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[tedad_karton] [smallint] NULL,
[sharayete_tasfieh] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[tarikh] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[noe_darkhast] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[gymat_kol_darkhast] [bigint] NULL,
[code_noae] [nvarchar] (4) COLLATE Persian_100_CI_AS NULL,
[takhfif_jenci] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[takhfif_naghdi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[takhfif_noe] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[bargashti] [int] NULL,
[Tedad_print] [tinyint] NULL,
[mablage_jayze_jenci] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[mablage_jayze_nagdi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Shomareh_Sanad] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Shomareh_Rasmi] [int] NULL,
[Darsad_Takhfif] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Meghdar_Takhfif] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Arzesh_afzodeh1] [decimal] (18, 3) NULL,
[Arzesh_afzodeh2] [decimal] (18, 3) NULL,
[Arzesh_afzodeh3] [decimal] (18, 3) NULL,
[Arzesh_afzodeh] [decimal] (18, 3) NULL,
[tarikh_tahvil] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[flag] [int] NULL,
[Flag_Sanad] [int] NULL,
[Flag_edit] [int] NULL,
[User_Edit] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[active] [bit] NULL,
[username] [nvarchar] (30) COLLATE Persian_100_CI_AS NULL,
[machine] [nvarchar] (40) COLLATE Persian_100_CI_AS NULL,
[date_time] [nvarchar] (50) COLLATE Persian_100_CI_AS NULL,
[Darsad_takhfif_naghdi] [decimal] (6, 2) NULL,
[Darsad_takhfif_noe] [decimal] (6, 2) NULL,
[Rate] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Darsad_Takhfif_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_fa_Darsad_Takhfif_Saderat] DEFAULT ((0)),
[Takhfif_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_fa_Takhfif_Saderat] DEFAULT ((0)),
[Add_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_fa_Add_Saderat] DEFAULT ((0)),
[Darsad_Add_Saderat] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL CONSTRAINT [DF_fa_Darsad_Add_Saderat] DEFAULT ((0)),
[Takhfif_Kol] [decimal] (18, 0) NULL,
[Mablagh_PassAZ_Takhfif] [decimal] (18, 0) NULL,
[Mablagh_Malyat] [decimal] (18, 0) NULL,
[Mablagh_Kol_BaMalyat] [decimal] (18, 0) NULL,
[Mablagh_Kol_Takhfif] [decimal] (18, 0) NULL,
[Counter] [bigint] NOT NULL IDENTITY(1, 1),
[Tarikh_Taeid_Rasmi] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Person_Taeid_Rasmi] [nvarchar] (20) COLLATE Persian_100_CI_AS NULL,
[Rasteh] [int] NULL CONSTRAINT [DF__Factor__Rasteh__425CA323] DEFAULT ((0)),
[Shomareh_Sanad_Anbar] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[AppName] [nvarchar] (128) COLLATE Persian_100_CI_AS_SC_UTF8 NULL,
[Tedad_Rooz] [int] NULL,
[Rase_Factor] [nvarchar] (10) COLLATE Persian_100_CI_AS NULL,
[Date_Int] [int] NULL,
[IsFestival] [bit] NULL,
[ShomarehFactor_Int] [int] NULL,
[Rase_Factor_Int] [int] NULL,
[IsOmdeh] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[factor] ADD CONSTRAINT [ChkSerial6] CHECK (([shomareh_serial] IS NOT NULL))
GO
